# Generated by Django 4.2.7 on 2023-11-16 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birthday_date',
            new_name='birth_date',
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.university'),
        ),
        migrations.AlterField(
            model_name='university',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='short_name',
            field=models.CharField(max_length=50),
        ),
    ]
